name: Generate Changelog on Tag
on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create/Update CHANGELOG.md
        uses: orhun/git-cliff-action@v3
        with:
          config: |
            [changelog]
            header = "# Changelog"
            body = """
            All notable changes to this project will be documented in this file.
            """
            trim = true
          args: -u --tag ${{ github.ref_name }} -o CHANGELOG.md

      - name: Commit changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${{ github.ref_name }}" || echo "No changes to commit"
          git push

